class NBAData {
  league = "NBA";
  away_team = {
    team_id: "oklahoma-city-thunder",
    abbreviation: "OKC",
    active: true,
    first_name: "Oklahoma City",
    last_name: "Thunder",
    conference: "West",
    division: "Northwest",
    site_name: "Chesapeake Energy Arena",
    city: "Oklahoma City",
    state: "Oklahoma",
    full_name: "Oklahoma City Thunder",
  };
  home_team = {
    team_id: "miami-heat",
    abbreviation: "MIA",
    active: true,
    first_name: "Miami",
    last_name: "Heat",
    conference: "East",
    division: "Southeast",
    site_name: "AmericanAirlines Arena",
    city: "Miami",
    state: "Florida",
    full_name: "Miami Heat",
  };
  away_period_scores = [0, 0, 0, 0];
  home_period_scores = [0, 0, 0, 0];
  away_stats = [
    {
      last_name: "Durant",
      first_name: "Kevin",
      display_name: "Kevin Durant",
      position: "SF",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "OKC",
      is_starter: true,
      field_goal_percentage: 0.00,
      three_point_percentage: 0.00,
      free_throw_percentage: 0.00,
    },
    {
      last_name: "Westbrook",
      first_name: "Russell",
      display_name: "Russell Westbrook",
      position: "PG",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "OKC",
      is_starter: true,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Ibaka",
      first_name: "Serge",
      display_name: "Serge Ibaka",
      position: "PF",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "OKC",
      is_starter: true,
      field_goal_percentage: 0.00,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.00,
    },
    {
      last_name: "Perkins",
      first_name: "Kendrick",
      display_name: "Kendrick Perkins",
      position: "C",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "OKC",
      is_starter: true,
      field_goal_percentage: 0.00,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Sefolosha",
      first_name: "Thabo",
      display_name: "Thabo Sefolosha",
      position: "SF",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "OKC",
      is_starter: true,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Harden",
      first_name: "James",
      display_name: "James Harden",
      position: "SG",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "OKC",
      is_starter: false,
      field_goal_percentage: 0.00,
      three_point_percentage: 0.00,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Fisher",
      first_name: "Derek",
      display_name: "Derek Fisher",
      position: "PG",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "OKC",
      is_starter: false,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Collison",
      first_name: "Nick",
      display_name: "Nick Collison",
      position: "PF",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "OKC",
      is_starter: false,
      field_goal_percentage: 0.00,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Cook",
      first_name: "Daequan",
      display_name: "Daequan Cook",
      position: "SG",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "OKC",
      is_starter: false,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Aldrich",
      first_name: "Cole",
      display_name: "Cole Aldrich",
      position: "C",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "OKC",
      is_starter: false,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Hayward",
      first_name: "Lazar",
      display_name: "Lazar Hayward",
      position: "SF",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "OKC",
      is_starter: false,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Ivey",
      first_name: "Royal",
      display_name: "Royal Ivey",
      position: "PG",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "OKC",
      is_starter: false,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
  ];
  home_stats = [
    {
      last_name: "James",
      first_name: "LeBron",
      display_name: "LeBron James",
      position: "SF",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "MIA",
      is_starter: true,
      field_goal_percentage: 0.00,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Wade",
      first_name: "Dwyane",
      display_name: "Dwyane Wade",
      position: "SG",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "MIA",
      is_starter: true,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Bosh",
      first_name: "Chris",
      display_name: "Chris Bosh",
      position: "PF",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "MIA",
      is_starter: true,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Chalmers",
      first_name: "Mario",
      display_name: "Mario Chalmers",
      position: "PG",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "MIA",
      is_starter: true,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Battier",
      first_name: "Shane",
      display_name: "Shane Battier",
      position: "SF",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "MIA",
      is_starter: true,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Miller",
      first_name: "Mike",
      display_name: "Mike Miller",
      position: "SF",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "MIA",
      is_starter: false,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Cole",
      first_name: "Norris",
      display_name: "Norris Cole",
      position: "PG",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "MIA",
      is_starter: false,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Haslem",
      first_name: "Udonis",
      display_name: "Udonis Haslem",
      position: "PF",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "MIA",
      is_starter: false,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Jones",
      first_name: "James",
      display_name: "James Jones",
      position: "SF",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "MIA",
      is_starter: false,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Howard",
      first_name: "Juwan",
      display_name: "Juwan Howard",
      position: "PF",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "MIA",
      is_starter: false,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Turiaf",
      first_name: "Ronny",
      display_name: "Ronny Turiaf",
      position: "C",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "MIA",
      is_starter: false,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
    {
      last_name: "Harris",
      first_name: "Terrel",
      display_name: "Terrel Harris",
      position: "SG",
      minutes: 0,
      points: 0,
      assists: 0,
      turnovers: 0,
      steals: 0,
      blocks: 0,
      field_goals_attempted: 0,
      field_goals_made: 0,
      three_point_field_goals_attempted: 0,
      three_point_field_goals_made: 0,
      free_throws_attempted: 0,
      free_throws_made: 0,
      defensive_rebounds: 0,
      offensive_rebounds: 0,
      personal_fouls: 0,
      team_abbreviation: "MIA",
      is_starter: false,
      field_goal_percentage: 0.0,
      three_point_percentage: 0.0,
      free_throw_percentage: 0.0,
    },
  ];
  officials = [
    {
      position: null,
      first_name: "Derrick",
      last_name: "Stafford",
    },
    {
      position: null,
      first_name: "Dan",
      last_name: "Crawford",
    },
    {
      position: null,
      first_name: "Monty",
      last_name: "McCutchen",
    },
  ];
  event_information = {
    temperature: 0,
    site: {
      capacity: 19600,
      surface: "Hardwood",
      name: "AmericanAirlines Arena",
      state: "Florida",
      city: "Miami",
    },
    attendance: 20003,
    duration: 0,
    status: "completed",
    season_type: "post",
    start_date_time: Date.now(),
  };
  away_totals = {
    minutes: 0,
    points: 0,
    assists: 0,
    turnovers: 0,
    steals: 0,
    blocks: 0,
    field_goals_attempted: 0,
    field_goals_made: 0,
    three_point_field_goals_attempted: 0,
    three_point_field_goals_made: 0,
    free_throws_attempted: 0,
    free_throws_made: 0,
    defensive_rebounds: 0,
    offensive_rebounds: 0,
    personal_fouls: 0,
    field_goal_percentage: 0.0,
    three_point_percentage: 0.0,
    free_throw_percentage: 0.0,
  };
  home_totals = {
    minutes: 0,
    points: 0,
    assists: 0,
    turnovers: 0,
    steals: 0,
    blocks: 0,
    field_goals_attempted: 0,
    field_goals_made: 0,
    three_point_field_goals_attempted: 0,
    three_point_field_goals_made: 0,
    free_throws_attempted: 0,
    free_throws_made: 0,
    defensive_rebounds: 0,
    offensive_rebounds: 0,
    personal_fouls: 0,
    field_goal_percentage: 0.0,
    three_point_percentage: 0.0,
    free_throw_percentage: 0.0,
  };
}

module.exports = NBAData